name: Porter cred test Pipeline

on:
  push:
    branches:
      - main

jobs:
  porter-cred-Install:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Porter
        run: |
          Invoke-WebRequest -Uri "https://cdn.porter.sh/latest/install-windows.ps1" -UseBasicParsing | iex
          $env:PATH+=";$env:USERPROFILE\.porter" 
          # curl -L https://cdn.porter.sh/latest/install-linux.sh | bash
          # export PATH=$PATH:~/.porter
          porter --version
          porter mixin install terraform 
          porter mixin install docker 
          docker login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker pull docker/dockerfile-upstream:1.4.0
          porter build
          porter credentials apply github.json
          $env:GITHUB_TOKEN="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"
          porter install -c github.json
          porter installation show
     
      
     
      
