name: Porter cred test Pipeline

on:
  push:
    branches:
      - main

jobs:
  porter-cred-Install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Porter
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
        run: |
          curl -L https://cdn.porter.sh/latest/install-linux.sh | bash
          export PATH=$PATH:~/.porter
          porter --version
          porter mixin install terraform 
          porter mixin install docker 
          # docker login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          # docker pull docker/dockerfile-upstream:1.4.0
          # porter build
          porter credentials apply github.json
          export GITHUB_TOKEN= $GITHUB_TOKEN
          echo "hello" GITHUB_TOKEN: $GITHUB_TOKEN
          chmod +x ./helpers.sh
          porter install -c github
          porter installation show
     
      
     
      
